sonar.projectKey=pet-find
sonar.projectName=pet-find
sonar.host.url=http://sonarqube:9000
sonar.token=${SONAR_TOKEN}
sonar.scm.disabled=true
sonar.modules=bff-service,user-service,pet-service,geoservice,match-service

# Per-module config
bff-service.sonar.projectBaseDir=apps/bff-service
bff-service.sonar.sources=src/main/kotlin
bff-service.sonar.java.binaries=build/classes
bff-service.sonar.tests=src/test/kotlin
bff-service.sonar.junit.reportPaths=build/test-results/test
bff-service.sonar.testExecutionReportPaths=build/reports/tests
bff-service.sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml

user-service.sonar.projectBaseDir=services/user-service
user-service.sonar.sources=src/main/kotlin
user-service.sonar.java.binaries=build/classes
user-service.sonar.tests=src/test/kotlin
user-service.sonar.junit.reportPaths=build/test-results/test
user-service.sonar.testExecutionReportPaths=build/reports/tests
user-service.sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml

pet-service.sonar.projectBaseDir=services/pet-service
pet-service.sonar.sources=src/main/kotlin
pet-service.sonar.java.binaries=build/classes
pet-service.sonar.tests=src/test/kotlin
pet-service.sonar.junit.reportPaths=build/test-results/test
pet-service.sonar.testExecutionReportPaths=build/reports/tests
pet-service.sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml

geoservice.sonar.projectBaseDir=services/geoservice
geoservice.sonar.sources=src/main/kotlin
geoservice.sonar.java.binaries=build/classes
geoservice.sonar.tests=src/test/kotlin
geoservice.sonar.junit.reportPaths=build/test-results/test
geoservice.sonar.testExecutionReportPaths=build/reports/tests
geoservice.sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml

match-service.sonar.projectBaseDir=services/match-service
match-service.sonar.sources=src/main/kotlin
match-service.sonar.java.binaries=build/classes
match-service.sonar.tests=src/test/kotlin
match-service.sonar.junit.reportPaths=build/test-results/test
match-service.sonar.testExecutionReportPaths=build/reports/tests
match-service.sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
