spring:
  application:
    name: match-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8084

rabbitmq:
  exchange: sanos-salvos.exchange
  queue:
    pet-reports: match.mascota.reportada
  routing-key:
    pet: mascota.reportada
    match: coincidencia.detectada
